apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: tensorflow-worker2}
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        name: tensorflow-worker2
        role: worker
    spec:
      containers:
      - name: worker
        image: tensorflow/tensorflow
        ports:
        - containerPort: 2222

